### PR TITLE
Fix the tests with libc 0.2.49 and Rust 1.33.0

### PR DESCRIPTION
**Pull request by asomers**
Several symbols are now marked as deprecated on OSX.

### CODE REVIEW

**Comment by asomers** [comment]
This should fix PR #1031

**Comment by asomers** [comment]
Can one of the @nix-rust/nix-maintainers with an OSX machine please verify whether Nix 0.13.0 can even build with libc 0.2.49?

**Comment by asomers** [comment]
Ok, I'm stumped.  Why didn't the `#[allow(deprecated)]` fix the tests on OSX?

**Comment by Susurrus** [comment]
I have a machine and can dig into this tonight if that'd be helpful.

**Comment by asomers** [comment]
That would indeed be helpful.  But don't bother with my first question; 0.13.0 should still work fine, because we only `#[deny(warnings)]` during `#[cfg(test)]`.

**Comment by asomers** [comment]
Ok, I'm an idiot.  I never actually committed the important part.

**Comment by asomers** [comment]
The Linux failure looks like a regression in Cargo 1.32.0.  I'll fix it.

**Comment by asomers** [comment]
It looks like Cargo <= 1.32.0 would create a new thread for every test, even if `--test-threads=1`.  And in-between tests it would destroy the test thread and recreate it. But Cargo 1.33.0 skips creating a new thread when `--test-threads=1`.  And even if `--test-threads=1`, it reuses threads for multiple tests.  This has exposed a failure to teardown some per-thread data in one of our unit tests.

Weirdly, this is a case where `--test-threads=1` is _more_ likely to make the test fail.

**Pull request merged**
