### PR TITLE
Asomers kevent

### PR DESCRIPTION
**Pull request by posborne**
This is a rebase of @asomers work on master to resolve a merge conflict so we can get things merged up.

### CODE REVIEW

**Comment by posborne** [comment]
This replaces #442 so we can get things merged up.

**Comment by posborne** [comment]
@homu r+

**Comment by asomers** [comment]
@posborne should we update CHANGELOG.md to reference PR #453 instead of PR #442 ?

**Comment by posborne** [comment]
> @posborne should we update CHANGELOG.md to reference PR #453 instead of PR #442 ?

Nah, #422 is fine since that's where the comments are and there will be a link to this.  No worries.

**Pull request merged**
