### PR TITLE
Fix #411 - Provide accessors for 'events' in PollFd

### LINKED ISSUE #411: Provide read and write accessors for events in `PollFd`.
The motivation is given in #399.

### PR DESCRIPTION
**Pull request by cemeyer**
Test: `cargo test --test test test_pollfd_events`

### CODE REVIEW

**Review by asomers — COMMENTED** [review]
What's the motivation?  The `PollFd::events` method seems especially redundant.

**Comment by cemeyer** [comment]
[Some earlier discussion](https://github.com/nix-rust/nix/pull/399#issuecomment-243869050):
> Based on my own usage of poll in the past, it would be very useful to be able to modify poll interests. For instance, with non-blocking sockets, it is useful to register for POLLOUT to get notifications of when a socket connects and then unregister that interest later.

Not sure `events()` is redundant with anything -- e.g., if you want to modify a set of `PollFd`s in place and you didn't store the original flags elsewhere, how else would you reconstruct the opaque inner value?  But perhaps that is academic.  I'm fine dropping `events()` if you feel it is unnecessary.

**Review by asomers — APPROVED** [review]
I see.  When I said that `events` was redundant, I misread it.  This looks ok to me, though you'll have to rebase to fix the merge conflict.

**Comment by cemeyer** [comment]
Thanks!  Rebased.

**Review by asomers — APPROVED** [review]
bors r+

**Pull request merged**
