### PR TITLE
Fix documentation formating for pipe2

### PR DESCRIPTION
**Pull request by rusty-snake**

### CODE REVIEW

**Comment by asomers** [comment]
@rusty-snake this change looks good, but could you please rebase to fix the test failures?

**Comment by rusty-snake** [comment]
Rebase against what?

> This branch is 1 commit ahead of nix-rust:master.

**Comment by asomers** [comment]
Sorry, I spoke to soon.  But *now* you should rebase.

**Review by asomers — APPROVED** [review]
bors r+

**Pull request merged**
