### PR TITLE
Update `mman` related docs

### PR DESCRIPTION
**Pull request by schctl**
Added docs for `memfd_create`, `shm_open`, and `shm_unlink`, and some man-page and intra doc links.

### CODE REVIEW

**Review by asomers — COMMENTED** [review]
Thank you, this looks great!  If you also add docs for MemFdCreateFlag, then we can remove the #[allow(missing_docs)] for that file.

**Comment by schctl** [comment]
Alright, I'll add the changes soon.

**Comment by rtzoeller** [comment]
@asomers care to grant permission?

**Review by asomers — APPROVED** [review]
@rtzoeller try again

**Pull request merged**
