### PR TITLE
add libc::IP6T_SO_ORIGINAL_DST to socket opt

### PR DESCRIPTION
**Pull request by bearice**
the original PR #1410 was stalled for a while
let's make it happen.

this should closes #1410 and #938

### CODE REVIEW

**Comment by asomers** [comment]
What does that sockopt do, anyway?  I can't find it in any man pages.

**Comment by bearice** [comment]
It's an IPv6 version of SO_ORIGINAL_DST

**Review by asomers — APPROVED** [review]
bors r+

**Comment by asomers** [comment]
bors is confused. It doesn't realize that the iOS and OSX builds have finished.  Let's start over.

bors r-

**Comment by asomers** [comment]
bors retry

**Pull request merged**
