### PR TITLE
Implement symlinkat

### PR DESCRIPTION
**Pull request by oblique**

### CODE REVIEW

**Comment by asomers** [comment]
Does this `symlink` have any advantages over [std::os::unix::fs::symlink](https://doc.rust-lang.org/std/os/unix/fs/fn.symlink.html)?  If not, then I don't think we should provide a redundant binding.

**Comment by oblique** [comment]
No. However it is convenient when someone wants to write a function that returns `nix::Error`.

**Comment by asomers** [comment]
I don't think that's important enough to justify the bloat.  Please remove `symlink`.  Keep `symlinkat` though; that's useful.

**Comment by oblique** [comment]
Ready

**Pull request merged**
