### PR TITLE
Fixed typo in tcsetpgrp

### PR DESCRIPTION
**Pull request by zethra**

### CODE REVIEW

**Comment by fiveop** [comment]
Thanks. Since this was added after the last release, there is no need for a CHANGELOG entry.

@homu r+

**Comment by fiveop** [comment]
@homu r-

**Comment by fiveop** [comment]
Could you revert the second commit and open a new PR for the added functions? It also looks like you would need to amend libc first, because they have no bindings for setpgrp, etc.

**Comment by fiveop** [comment]
In order to skip the two unnecessary commits, please `git reset` your local branch to the first commit (`git reset --mixed`) and force push to the your github branch from wich you try to merge (`git push -f origin master` probably).

**Comment by zethra** [comment]
Done

**Comment by posborne** [comment]
@homu r=fiveop

**Pull request merged**
