### PR TITLE
Update to cfg-if 1.0

### PR DESCRIPTION
**Pull request by mbrubeck**

### CODE REVIEW

**Comment by asomers** [comment]
Why?  What is the benefit?

**Comment by mbrubeck** [comment]
The only change in this release is alexcrichton/cfg-if#37, which removes some syntax that was inconsistent with the standard `cfg` macro and attributes.

There's no urgent reason to update right away, but once everyone has updated to latest version, it will reduce the need for downstream crates to download and compile two different versions of `cfg-if`.  It will also let users of this library automatically benefit from fixes in any future 1.x release of `cfg-if`.

**Review by asomers — APPROVED** [review]
bors r+

**Comment by asomers** [comment]
bors retry

**Comment by lopopolo** [comment]
@asomers is it possible to get an 0.19 point release that contains this dep bump? I'm trying to update all of my transitive dependencies to cfg-if v1.

**Comment by asomers** [comment]
Yes.  In fact, I would really like to do a point release just for #1337

**Comment by asomers** [comment]
https://crates.io/crates/nix/0.19.1

**Pull request merged**
