### PR TITLE
Derive `Ord`, `PartialOrd` for `Pid`

### LINKED ISSUE #1188: Derive `Ord`, `PartialOrd` for `Pid`
This would enable, for example, keying `BTree{Map,Set}` on a `Pid` without having to invoke `{as,from}_raw()`, or adding a wrapper around `Pid` itself.

It looks like these traits are currently missing on all platforms.

I'm running:
- **Platform:** x86-64, Linux 5.4
- **rustc:** 1.41.0

### PR DESCRIPTION
**Pull request by ranweiler**
Closes #1188.

### CODE REVIEW

**Comment by posborne** [comment]
Bah, bors r+

**Comment by ranweiler** [comment]
@posborne, would you like me to add a changelog entry with this PR, or do maintainers prefer to do that separately post-merge?

**Comment by posborne** [comment]
@ranweiler Yes, good call.  We do prefer them to be a part of the PR.  Looks like things didn't go through before so go ahead and add now.

**Comment by ranweiler** [comment]
@posborne added!

**Comment by posborne** [comment]
Thanks @ranweiler, looks good.  Can you squash down to a single commit and then I'll kick off the merge.

**Comment by ranweiler** [comment]
@posborne done.

**Pull request merged**
