### PR TITLE
Fix TODO: exclude fdatasync from Apple systems

### PR DESCRIPTION
**Pull request by jabedude**
Small PR to fix a TODO in unistd.rs.

Signed-off-by: Josh Abraham <sinisterpatrician@gmail.com>

### CODE REVIEW

**Comment by asomers** [comment]
Did you check whether libc defines fdatasync for dragonfly BSD?

**Comment by asomers** [comment]
And openbsd too. Neither of those is checked in ci.

**Comment by jabedude** [comment]
Sure thing, looks like it is not defined for fdatasync and is defined for openbsd. I'll go ahead and exclude it.

**Comment by asomers** [comment]
Could you please add a mention to the CHANGELOG?

**Comment by jabedude** [comment]
Sure thing, done!

**Comment by asomers** [comment]
The CHANGELOG entry got inserted into the wrong section; probably a merge error on your side.  Please move it up to the `[Unreleased]` section.  And I would put it under `Fixed` rather than `Changed`.  The latter suggests that some action might be required by a user when upgrading.  Do that and squash the commits, and I'll merge it.

**Comment by asomers** [comment]
Please squash the commits, too.

**Pull request closed without merging**
