### PR TITLE
Enable creating a const TimeSpec

### PR DESCRIPTION
**Pull request by danieldulaney**
Previously, there was no way to create a `TimeSpec` in a `const` context because all creation was through traits. This adds two utility functions to create a `const TimeSpec` from a `libc::timespec` or an `std::time::Duration`.

An alternative approach would be to make the inner `timespec` field `pub`, which would not require any additional functions but would expose some (potentially unwanted) implementation details.

### CODE REVIEW

**Review by asomers — CHANGES_REQUESTED** [review]
I think this looks good.  Would you mind adding a CHANGELOG entry?

**Comment by danieldulaney** [comment]
I think this is the correct way to add an entry -- is this the first change for this version?

**Review by asomers — APPROVED** [review]
Yep, that's correct.

**Review by asomers — APPROVED** [review]
bors r+

**Pull request merged**
