### PR TITLE
add the TCP_INFO constant for NetBSD/FreeBSD.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Review by asomers — COMMENTED** [review]
tcp_info is tricky, because it is a version-dependent structure.  The size at least is constant for FreeBSD 6 through 14.  But it grows on FreeBSD 15.  It isn't really meant to be used across different OS versions.  Probably the best way to use it from Rust would be to run bindgen at build time (which of course precludes cross-compiling).  Given that, is it really safe to include in Nix?

**Comment by devnexen** [comment]
For FreeBSD, it ensures the size remains the same through versions (at least until it reaches the limit of the padding) or do you mean something else ?

**Comment by asomers** [comment]
That's just the thing; in FreeBSD 15 the size increases.

**Comment by devnexen** [comment]
oh I see yes the layout had been changed a bit this year.

**Pull request closed without merging**
