### PR TITLE
linux: Add sendfile(2)

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
r? @arcnmx 
since why not

**Comment by kamalmarhubi** [comment]
@homu r? @arcnmx

**Comment by kamalmarhubi** [comment]
hrm

**Comment by kamalmarhubi** [comment]
Oh, r? is part of rust-highfive I think.

**Comment by kamalmarhubi** [comment]
r+

**Comment by kamalmarhubi** [comment]
@homu r+

**Comment by kamalmarhubi** [comment]
@homu r-

**Comment by kamalmarhubi** [comment]
woo it works

**Comment by kamalmarhubi** [comment]
@arcnmx would you mind taking a look? :-)

**Comment by arcnmx** [comment]
Where's test_sendfile? o:

**Comment by kamalmarhubi** [comment]
oh dear rebase fail

**Comment by kamalmarhubi** [comment]
@arcnmx fixed

**Comment by arcnmx** [comment]
Pretty straightforward, looks good! My only comment is that the test would deadlock on a system without buffered pipes, but that's not the case on Linux so..!

@homu r+

**Comment by arcnmx** [comment]
Fancy, it used an older test result o:

**Comment by kamalmarhubi** [comment]
Cool!

@arcnmx out of curiosity, what common systems don't have buffered pipes?

**Comment by arcnmx** [comment]
No idea, probably none, but it's not specified so it's somewhat like relying on implementation details.

> Applications should not rely on a particular capacity: an application should be designed so that a reading process consumes data as soon as it is available, so that a writing process does not remain blocked.

**Pull request merged**
