### PR TITLE
sendmsg: Fix padding for ControlMessages, and zero it rather than leave it uninitialised

### PR DESCRIPTION
**Pull request by alecmocatta**
I hit a valgrind complaint sending a single fd over a single ControlMessage. Nix was handing a length including padding to the `sendmsg` syscall, but the padding bytes were unaddressable (i.e. not just uninitialised, but after the end of the Vec, which is not good).

This fixes that. It possibly fixes/affects #756, as the old behaviour of not padding between ControlMessages despite the padded length being what's passed to the syscall seemed wrong. That however is yet to be tested.

Feel free to not accept until I/someone else gets a chance to more thoroughly test, I'm making it so that if someone else bumps into this problem they have something to go on in the meantime.

### CODE REVIEW

**Comment by asomers** [comment]
Thanks for the bug report.  Could you also please add a test case that demonstrates the problem?  Perhaps a unit test for `encode_into`?

**Comment by przygienda** [comment]
Sigh, the encoding seems to be broken beyond a single cmsg. When several cmsg are given only first is encoded but the size blows up to the point kernel starts to throw back excessive length. On top copy seems to be weird as well, it seems to copy @ the end. In short, it shows there are not unit tests for that stuff ...  Yes, unit-test for encode_into needed ...

**Comment by przygienda** [comment]
Did more work & IMO there's a clear bug when you add stuff where cmsg.len() is not = cmsg.size(). Here's the necessary diff ... After I fixed that one multiple CMESG started to work so it seems the padding alignment code is actually working ...  

```
pub fn sendmsg<'a>(fd: RawFd, iov: &[IoVec<&'a [u8]>], cmsgs: &[ControlMessage<'a>], flags: MsgFlags, addr: Option<&'a SockAddr>) -> Result<usize> {
    let mut capacity = 0;
    for cmsg in cmsgs {
        capacity += cmsg.space();
    }
    // Note that the resulting vector claims to have length == capacity,
    // so it's presently uninitialized.
    let mut cmsg_buffer = unsafe {
        let mut vec = Vec::<u8>::with_capacity(capacity);
        vec.set_len(capacity);
        vec
    };
    {
        let mut ofs = 0;
        for cmsg in cmsgs {
            let mut ptr = &mut cmsg_buffer[ofs ..];
            unsafe { cmsg.encode_into(&mut ptr) };
            ofs += cmsg.space();
        }
    }
```

**Comment by asomers** [comment]
Thanks for tracking this down!  Could you please submit your change in PR form, along with a test case?

**Pull request closed without merging**
