### PR TITLE
Raise minimum supported Rust version to 1.36.0

### PR DESCRIPTION
**Pull request by otavio**
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Comment by otavio** [comment]
@asomers I rebased this on top of current master; please take a look.

**Comment by asomers** [comment]
Please note in the commit message the reason for raising the msrv.  Otherwise, it looks good.

**Comment by otavio** [comment]
It is, on the long description.

**Comment by asomers** [comment]
Ahh, my apologies.  I didn't see it on my tiny cell phone screen.  I'll take a look at the musl failure.

**Pull request merged**
