### PR TITLE
Fix Clippy warnings on FreeBSD with the latest nightly

### PR DESCRIPTION
**Pull request by asomers**
* Better type safety for mqueue
* Suppress clippy::not_unsafe_ptr_arg_deref warnings in ptrace on BSD

### CODE REVIEW

**Comment by asomers** [comment]
Supersedes #1638

**Comment by lucab** [comment]
POSIX does explicitly mention that `A message queue descriptor may be implemented using a file descriptor`, which I think is the case at least on Linux.
Before this, it used to be possible to check an existing open file-descriptor via `getattr` and then convert it to a message queue descriptor. Would it be possible to get that functionality back, on specific platforms? How should that look like?

**Comment by asomers** [comment]
@lucab could you give an example in Rust, C, or pseudocode?  How would that feature work?

**Comment by lucab** [comment]
Sure, and thanks for the prompt reply!
The initial context here is `systemd`, which is a Linux-only service manager.
It supports listening on a message queue (or socket/FIFO/etc.) on behalf of a service and activating it on demand, see <https://www.freedesktop.org/software/systemd/man/systemd.socket.html#ListenMessageQueue=>.
The activation mechanism works in a way such that systemd performs the `mq_open()`, then later passes the open file-descriptor to the spawned service/process.
The spawned process here would be a Rust binary, and we have a library method `is_mq()` to check the inherited FD. It is built on top of the previous design of `nix::mqueue::mq_getattr()`, see https://docs.rs/libsystemd/latest/libsystemd/activation/trait.IsType.html#method.is_mq.
Overall I'm not particularly attached to the existing code/design, but I feel that we are now missing primitives for fallible conversion between a file-descriptor and a mqueue-descriptor.

**Comment by rtzoeller** [comment]
> I feel that we are now missing primitives for fallible conversion between a file-descriptor and a mqueue-descriptor.

I think it's worth noting that the conversion itself was infallible. You could end up with an invalid mqueue-descriptor, as `libsystemd` handled, but the conversion still succeeded. I don't think nix can make the conversion fallible without performing a similar syscall, and don't think it needs to.

[`std::os::unix::io::FromRawFd`](https://doc.rust-lang.org/nightly/std/os/unix/io/trait.FromRawFd.html) is surprising unhelpful for you, as it takes ownership and `is_mq()` takes an immutable reference. Consequently I think we'll need to implement at least [`std::convert::From`](https://doc.rust-lang.org/std/convert/trait.From.html).

Implementing [`std::os::unix::io::AsRawFd`](https://doc.rust-lang.org/nightly/std/os/unix/io/trait.AsRawFd.html) and [`std::os::unix::io::IntoRawFd`](https://doc.rust-lang.org/nightly/std/os/unix/io/trait.IntoRawFd.html) gets you from an `MqdT` to a `RawFd` (which isn't what you need), but IMO is worth doing for symmetry.

We should probably implement all four traits on Linux and any other platforms that use FDs instead of pointers for `mqd_t`, unless @asomers sees a reason not to.

**Pull request merged**
