### PR TITLE
Fix #1093

### LINKED ISSUE #1093: exec family functions take CString instead of &CStr
For example, the signature of `execve` is:

    pub fn execve(path: &CString, args: &[CString], env: &[CString]) -> Result<Void>

Surely there's no point in taking a `&CString` as opposed to a `&CStr`, right? And couldn't the slices just contain `&CStr`s since it's not possible to move out of a slice anyway?

### PR DESCRIPTION
**Pull request by tathanhdinh**
Hello,
This PR fixes the problem discovered in #1093.
Thanks for any comment.

### CODE REVIEW

**Comment by tathanhdinh** [comment]
Thank you for the feedback. CHANGELOG modified.

**Comment by asomers** [comment]
Looks good now.  As soon as PR #1123 is done, you'll be able to rebase this one and the test failures will be fixed.

**Comment by tathanhdinh** [comment]
Thank you. I'm wating for PR #1123 now.

**Comment by asomers** [comment]
You should be able to rebase now.

**Comment by tathanhdinh** [comment]
Thank you. The PR is rebased.

**Comment by otavio** [comment]
@tathanhdinh the commit log could receive some love, don't you think?

I know the issue is detailed but it'd be good if the commit log could be extended with it.

**Pull request merged**
