### PR TITLE
Remove deprecated items

### PR DESCRIPTION
**Pull request by SteveLauC**
#### What this pr does
1. Convert `assert!(x == y)` to `assert_eq!(x, y)`
2. Convert `assert!(x != y)` to `assert_ne!(x, y)`
3. Add `.unwrap()` to unused `Result/Option` (in code comments)
4. Convert `std::ixx::MAX` to `ixx::MAX`
5. Convert `Box<Trait>` to `Box<dyn Trait>`

### CODE REVIEW

**Comment by SteveLauC** [comment]
Almost all the CI tests failed. 

```shell
error: failed to compile `cargo-hack v0.5.14`, intermediate artifacts can be found at `/tmp/cargo-installtsdEE2`

Caused by:
  failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.143/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature

Exit status: 101
```

It seems to be related to the Rust toolchain

**Review by asomers — APPROVED** [review]
LGTM.  Was this suggested by some automated tool?
CI will be broken until serde publishes a new crate.

**Comment by SteveLauC** [comment]
> Was this suggested by some automated tool?

Yep, by [Intellij Rust](https://github.com/intellij-rust/intellij-rust)

> CI will be broken until serde publishes a new crate.

That's fine:)

**Comment by asomers** [comment]
rebase please

**Review by asomers — APPROVED** [review]
bors r+

**Pull request merged**
