### PR TITLE
wait: support ptrace events for Linux

### PR DESCRIPTION
**Pull request by abbradar**
Part of #270 -- see https://github.com/abbradar/nix-rust/commit/b2d3b4afa07bd97e4b842ffc0be57cf0ed3e636b for previous discussion.

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Copying part of my comment on the previous discussion:

> I'm also a bit put off by adding a meaningless member on non-Linux systems. Trying to think of alternatives...

I'm going to hold off on this for a bit while I think about stuff related to #190. :-)

**Comment by kamalmarhubi** [comment]
Coming back to this, I'd be happier if the extra variant and methods were `cfg`'ed to only be present on Linux, or whichever systems support it.

**Comment by luser** [comment]
I was thinking about this again, and how to handle this in a way that isn't terrible across platforms. What would you think about adding another entry to the `WaitStatus` enum, like `WaitStatus::PtraceEvent`? Then the `if status::stopped` case could check for this and return that value. It'd still be useless on non-Linux systems, but it seems like it'd be easier to work with a platform-conditional enum variant than a conditional field *inside* an enum variant. `#[cfg(...)]` seems to work OK on enum variants and match arms:
https://play.rust-lang.org/?gist=15519135f09722bf6d8653912592c079&version=stable&backtrace=0

**Comment by abbradar** [comment]
Sigh, I _still_ haven't returned to this (haven't actually got a chance to touch Rust for a long time already). I understand that this can be frustrating, and also -- if anyone wants to continue this work please do so!

I hope I can return to this someday...

**Comment by kamalmarhubi** [comment]
@abbradar this is not frustrating at all! And thanks for your contributions :-)

**Comment by kamalmarhubi** [comment]
@luser 
> What would you think about adding another entry to the `WaitStatus` enum, like `WaitStatus::PtraceEvent`? 

Could you sketch out what you mean a tiny bit?

**Comment by luser** [comment]
Oh, I can do you one better! I actually wrote the patch because I wanted to use it for something, I just forgot to do anything with it. Here it is:
https://github.com/luser/nix/commit/92a3cf77265e7402c555ab77d0ae3e3920914d36

Here's the code I wrote that uses it:
https://github.com/luser/tracetree/blob/master/src/main.rs#L65

I didn't actually try to make that code portable yet, but making it build should be straightforward. (Making it actually work right is probably harder).

**Comment by Susurrus** [comment]
Is this still relevant? If so, @abbradar would you be willing to update this patch?

**Comment by luser** [comment]
This was superseded by https://github.com/nix-rust/nix/pull/438

You can see an example of using it here: https://github.com/luser/tracetree/blob/2dcde59a9b2bd8dd6343a147a6d09f5d4428068e/src/main.rs#L141

**Comment by Susurrus** [comment]
Okay, then I'm going to close this. Thanks, @luser.

**Pull request closed without merging**
