### PR TITLE
Fix `num_microseconds` impl for `TimeSpec`

### PR DESCRIPTION
**Pull request by birkenfeld**

### CODE REVIEW

**Review by asomers — CHANGES_REQUESTED** [review]
CHANGELOG entry, please.

**Comment by birkenfeld** [comment]
Done.

**Review by asomers — APPROVED** [review]
bors r+

**Comment by kamalmarhubi** [comment]
bots r+

**Comment by kamalmarhubi** [comment]
bors r+

retrying

**Comment by asomers** [comment]
Superseded by #1801

**Pull request closed without merging**
