### PR TITLE
[skip ci] fix CHANGELOG formatting

### PR DESCRIPTION
**Pull request by asomers**

### CODE REVIEW

**Review by rtzoeller — APPROVED** [review]
bors r+

**Comment by rtzoeller** [comment]
Speaking of changelogs, @asomers how do you feel about me importing the patch release changelog notes into `master` once we're done with them?

We've been inconsistent with this in the past, and it makes it difficult to tell if a change was fixed in a given patch release - you have to navigate to the correct branch first.

**Comment by asomers** [comment]
> Speaking of changelogs, @asomers how do you feel about me importing the patch release changelog notes into `master` once we're done with them?
> 
> We've been inconsistent with this in the past, and it makes it difficult to tell if a change was fixed in a given patch release - you have to navigate to the correct branch first.

Definitely.  We should merge all of the patch releases' CHANGELOG notes.  I'll try to do that now.

**Comment by asomers** [comment]
And bors doesn't understand [skip ci].  We'll have to merge manually.

bors r-

**Pull request merged**
