### PR TITLE
Update to memoffset 0.7

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by rtzoeller** [comment]
@asomers I had a hard time tracking down a changelog for `memoffset`, but a quick perusal through the [git history](https://github.com/Gilnaa/memoffset/commits/master) looks fairly innocuous. Mostly doc/test updates, but they did add support for unions.

Any reason we shouldn't pull this in for 0.26.0?

**Comment by asomers** [comment]
Perhaps a bigger question is, why _should_ we bring it in at all?  What's the motivation for the change, @sdroege ?

**Comment by rtzoeller** [comment]
> Perhaps a bigger question is, why _should_ we bring it in at all? What's the motivation for the change, @sdroege ?

We are one of the most-used dependencies on `memoffset` (https://lib.rs/crates/memoffset/rev), and us being pinned to 0.6 may keep others from being able to use a newer version due to the semver being less than 1.0.

**Comment by asomers** [comment]
> We are one of the most-used dependencies on `memoffset` (https://lib.rs/crates/memoffset/rev), and us being pinned to 0.6 may keep others from being able to use a newer version due to the semver being less than 1.0.

That makes sense.  I had hoped to hear the author's motivation.  But I want to get 0.26.0 out soon, and don't want to wait.

**Review by asomers — APPROVED** [review]
bors r+

**Comment by sdroege** [comment]
> We are one of the most-used dependencies on `memoffset` (https://lib.rs/crates/memoffset/rev), and us being pinned to 0.6 may keep others from being able to use a newer version due to the semver being less than 1.0.

Yes exactly that. Because of `nix` I had multiple versions of `memoffset` in the dependency tree of a few of my crates.

**Pull request merged**
