### PR TITLE
travis: only require sudo on docker/i686 builds

### PR DESCRIPTION
**Pull request by posborne**
Signed-off-by: Paul Osborne <osbpau@gmail.com>

### CODE REVIEW

**Comment by posborne** [comment]
Based on http://stackoverflow.com/questions/34668468/use-sudo-true-with-single-element-of-build-matrix-in-travis-ci

**Comment by posborne** [comment]
With the added coverage, this certainly doesn't make things faster (especially at peak hours), but it is faster than it would be for the same amount of coverage using sudo for everything.

r? @kamalmarhubi

**Comment by posborne** [comment]
Ping @kamalmarhubi

**Comment by kamalmarhubi** [comment]
Ooh! I didn't know you could specify `sudo` per-matrix entry. Nice!

@homu r+ a6967d6

**Pull request merged**
