### PR TITLE
Support powerpc64

### PR DESCRIPTION
**Pull request by lu-zero**
The test_ioctl values are computed using ioctl-test.c

### CODE REVIEW

**Comment by Susurrus** [comment]
This is blocking on #590. Once we're using `cross`/`trust` to do cross-platform testing, we can enable `powerpc64`. That should be part of this PR once we merge #590.

**Comment by Susurrus** [comment]
Now that #590 is merged and we're using `cross`, let's go ahead and add PowerPC64 to the test framework as well. Please rebase these commits on top of the latest HEAD on top of adding `powerpc64` to the Travis CI tests.

**Comment by Susurrus** [comment]
@lu-zero Are you still interested in getting this merged? Just wanted to check in since it's been a while on this.

**Comment by lu-zero** [comment]
I had been busy, if you can point me to the test harness I can have a look.

**Comment by Susurrus** [comment]
@lu-zero Was gonna point you to the right spot, but it looks like you found it! This is close to ready, but could you update the README adding powerpc64/64le to the Tier1 list? And also squash this into one commit?

Once that's done, this is RTM.

**Comment by lu-zero** [comment]
great :) I was afraid I was missing something, let me know if the update is fine. (changed to keep the lines grouped)

**Pull request merged**
