### PR TITLE
unistd: Use bindings from libc instead of our own

### PR DESCRIPTION
**Pull request by kamalmarhubi**
Refs https://github.com/nix-rust/nix/issues/264

### CODE REVIEW

**Comment by posborne** [comment]
Looks like travis is undergoing maintenance.  Changes look good though.  @homu r+

**Comment by posborne** [comment]
P.S. @kamalmarhubi  You should take a look at https://github.com/nix-rust/nix/pull/292.  It seems to solve the test instabilities (although we may settle on another solution long term).

**Comment by kamalmarhubi** [comment]
OS X failure is for `fdatasync` missing, though it's part of POSIX. libc crate only includes it for linux and android, so I have included it for only those systems. I've sent a PR to libc to add it to more platforms:

https://github.com/rust-lang/libc/pull/211

**Comment by kamalmarhubi** [comment]
@homu retry

**Comment by kamalmarhubi** [comment]
@homu retry 6b24f60

**Comment by kamalmarhubi** [comment]
oh I see

@homu r=@posborne b24f60

**Comment by kamalmarhubi** [comment]
@homu r=@posborne 6b24f60

**Pull request merged**
