### PR TITLE
feat #1733: add F_GET_SEALS and F_ADD_SEALS on FreeBSD

### LINKED ISSUE #1733: fcntl F_SEAL not available on FreeBSD
https://github.com/nix-rust/nix/blob/16471898160b5b1fa27689a26727d1d82ddd5573/src/fcntl.rs#L437-L440

[FreeBSD manual](https://www.freebsd.org/cgi/man.cgi?query=fcntl&sektion=2) lists those as available, but `nix` does not.

### PR DESCRIPTION
**Pull request by SteveLauC**
Closes #1733

### CODE REVIEW

**Review by asomers — APPROVED** [review]
LGTM.  However, I'm not going to merge it yet because CI will fail (see https://github.com/serde-rs/serde/issues/2255).

**Comment by SteveLauC** [comment]
> LGTM. However, I'm not going to merge it yet because CI will fail (see [serde-rs/serde#2255](https://github.com/serde-rs/serde/issues/2255)).

That's fine, let's wait:)

**Comment by asomers** [comment]
rebase please

**Comment by SteveLauC** [comment]
@asomers This is ready to merge

**Comment by rtzoeller** [comment]
@SteveLauC it looks like there are three commits modifying the same lines - can you squash them?

**Comment by SteveLauC** [comment]
@rtzoeller sure thing! done.

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
