### PR TITLE
Update use of libc::timespec to prepare for future libc version (0.24 backport)

### PR DESCRIPTION
**Pull request by wesleywiser**
This is a backport of 006fc6f7975b3a6b64329847b780622aab392109. The original commit message follows:

In a future release of the `libc` crate, `libc::timespec` will contain private padding fields on `*-linux-musl` targets and so the struct will no longer be able to be created using the literal initialization syntax.

Update places where `libc::timespec` is created to first zero initialize the value and then update the `tv_sec` and `tv_nsec` fields manually. Many of these places are in `const fn`s so a helper function `zero_init_timespec()` is introduced to help with this as `std::mem::MaybeUninit::zeroed()` is not a `const` function.

Some matches on `libc::timespec` are also updated to include a trailing `..` pattern which works when `libc::timespec` has additional, private fields as well as when it does not (like for
`x86_64-unknown-linux-gnu`).

### CODE REVIEW

**Comment by rtzoeller** [comment]
Thanks! 

I plan to get the patch releases handled in the next few hours; I will likely just cherry pick these back though, rather than merging the PRs.

**Comment by wesleywiser** [comment]
Sounds good! I went ahead and provided the backports for all of (`0.25`, `0.24`, `0.23` and `0.22`) in various PRs. All of the backports required resolving some merge conflicts with the base branch so feel free to use them if you want 🙂 

I also tested that each built against current `i686-unknown-linux-musl`, `i686-unknown-linux-musl` with the musl 1.2 changes, `i686-unknown-linux-gnu`, `x86-64-unknown-linux-musl` and `x86-64-unknown-linux-gnu`.

**Comment by rtzoeller** [comment]
This was included in v0.24.3.

**Comment by rtzoeller** [comment]
@wesleywiser we still need to handle 0.23 and 0.22, but 0.25 and 0.24 are done. Thanks for backporting your change - it was helpful not to have to handle the merge conflicts for one of the commits myself! 😃

**Comment by wesleywiser** [comment]
@rtzoeller You're welcome, happy to help out! Thanks so much for including these 🙂

**Pull request closed without merging**
