### PR TITLE
Bump libc to 0.2.98

### PR DESCRIPTION
**Pull request by nox**
A new libc release with the MNT_ fixes was released.

### CODE REVIEW

**Comment by asomers** [comment]
The new libc release fixes what exactly?

**Comment by nox** [comment]
It includes the items that were needed for https://github.com/nix-rust/nix/pull/1453.

**Comment by nox** [comment]
Specifically, it includes https://github.com/rust-lang/libc/pull/2237, which you authored yourself. :p

**Review by asomers — APPROVED** [review]
Cool.  I thought that's probably what it was.  Thanks for the PR.

bors r+

**Comment by nox** [comment]
@asomers Can you do a 0.21.1 release afterwards please?

**Pull request merged**
