### PR TITLE
Improvements and new syscalls

### PR DESCRIPTION
**Pull request by abbradar**
This most likely should have been split for the review, but I don't see how except for maybe splitting each commit into its own PR -- each change is independent of other ones.

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
@abbradar thanks for the PR!

I'll review the commits in order. In the meantime, could you address the CI issues? Looks like unused var and import.

**Comment by kamalmarhubi** [comment]
@abbradar after looking, could you actually split each commit to its own PR? Some only have nits, others I'd rather hold off on. It's easier if I can merge each independently. Closing this in the meantime.

**Comment by abbradar** [comment]
No problem! Thank you very much for the review.

**Comment by kamalmarhubi** [comment]
:-)

**Comment by abbradar** [comment]
I've submitted things that required only small changes -- I'll work at others later.

**Pull request closed without merging**
