### PR TITLE
[skip ci] edit CHANGELOG formatting prior to 0.24.0 release

### PR DESCRIPTION
**Pull request by asomers**

### CODE REVIEW

**Comment by asomers** [comment]
Looks like Redox can no longer compile with the toolchain it recommends.  Maybe we should switch to standard nightly?

**Comment by rtzoeller** [comment]
> Looks like Redox can no longer compile with the toolchain it recommends.  Maybe we should switch to standard nightly?

I have no objections to switching to the latest nightly, or pinning to a more recent one.

**Comment by rtzoeller** [comment]
bors retry

**Review by rtzoeller — APPROVED** [review]

**Pull request merged**
