### PR TITLE
re-export RLIM_INFINITY from libc

### LINKED ISSUE #1803: Should maybe clarify that RLIM_INFINITY comes from libc
Doc for `getrlimit` and `setrlimit` mentions RLIM_INFINITY constant but doesn't mention it comes from the libc crate.
Maybe it should, or the constant could be re-exported in the `nix::sys::resource` namespace.
As it is now, search for RLIM_INFINITY in nix doc yields nothing, leaving user scratching his head :)

### PR DESCRIPTION
**Pull request by SteveLauC**
Fixes #1803

### CODE REVIEW

**Comment by SteveLauC** [comment]
PR #1830 was accidentally closed, but I didn't click that `close` button at all, seems to be a GitHub bug, so weird:(

**Review by rtzoeller — APPROVED** [review]
Thanks!

bors r+

**Comment by SteveLauC** [comment]
Test timed out, could we give it a retry?

**Comment by rtzoeller** [comment]
bors retry

**Comment by SteveLauC** [comment]
This is kinda weird, the test has been running for an hour. Perhaps there is something wrong with the CI?

**Comment by rtzoeller** [comment]
We'll see if it was a transient issue.

bors retry

**Pull request merged**
