### PR TITLE
backport a test to see if timestamps are working in aarch64

### PR DESCRIPTION
**Pull request by pacak**
Don't merge, this MR is to run the CI to see if we are getting the same errors as in https://github.com/nix-rust/nix/pull/1744

### CODE REVIEW

**Comment by rtzoeller** [comment]
bors try

**Comment by rtzoeller** [comment]
@pacak the test you're modifying currently builds for a few different platforms, but it looks like `ScmTimestampns` is only defined on Linux. You can ignore the failures on other platforms.

**Comment by rtzoeller** [comment]
Those checkout failures are odd though.

bors retry

**Comment by pacak** [comment]
The idea for this is to check if we can replicate the same problems on aarch64 as in https://github.com/nix-rust/nix/pull/1744 so I'm only interested in one result - aarch64. Or you think it makes sense to merge 
#1837 anyway?

**Comment by rtzoeller** [comment]
No, I wasn't suggesting merging this PR - I just was offering a suggestion to get rid of the other build failures to make it easier to parse the results.

**Comment by pacak** [comment]
If it's important - sure, I'll see what I can do

**Comment by rtzoeller** [comment]
This seems to be passing just fine on my aarch64 target. :/

**Comment by pacak** [comment]
> This seems to be passing just fine on my aarch64 target. :/

:thinking: and the new one still fails? I guess I'll go over the new branch one more time - maybe I'm doing something stupid and just managing to get away with it on non aarch64.

**Comment by rtzoeller** [comment]
> > This seems to be passing just fine on my aarch64 target. :/
> 
> thinking and the new one still fails? I guess I'll go over the new branch one more time - maybe I'm doing something stupid and just managing to get away with it on non aarch64.

I'm going to do another clean build against your new branch just to be sure.... just to make sure something didn't get screwed up during my uptaking of your latest changes. I'll let you know shortly.

**Comment by rtzoeller** [comment]
Yeah, confirmed the other branch (`pacak/master`) is still failing. Tested against the 5.19 kernel.

**Comment by rtzoeller** [comment]
Hmm, it looks like AWS Graviton has a free trial right now (with a fairly high compute limit, at least for this). I wonder if you'd be able to reproduce it there?

**Comment by pacak** [comment]
> I wonder if you'd be able to reproduce it there?

Probably, need to figure out what to do with it first :)

**Pull request closed without merging**
