### PR TITLE
Fix recvmmsg(2) implementation

### PR DESCRIPTION
**Pull request by codeslinger**
There were two problems discovered with the `recvmmsg(2)` implementation
that this changeset attempts to fix:

1. As mentioned in nix-rust/issues/1325, `recvmmsg(2)` can return fewer
   messages than requested, and
2. Passing the return value of `recvmmsg(2)` as the number of bytes in
   the messages received is incorrect.

This changeset incorporates the proposed fix from nix-rust/issues/1325,
as well as passing the correct value (`mmsghdr.msg_len`) for the number
of bytes in a given message.

### CODE REVIEW

**Comment by codeslinger** [comment]
I don't quite understand why the CI didn't pass on stable. On my Linux machine, the `test-aio-drop` test passes. It appears to be failing on other open PRs against this repo, as well, without any associated changes to anything that would affect that test.

**Comment by asomers** [comment]
Do you know of any way to force the condition described in #1325, so we can test for it?

**Comment by asomers** [comment]
BTW, the failure of test-aio-drop is not related to this PR.  I suspect it's due to a bug in glibc.  But I've never been able to reproduce it locally, so I'm not sure.

**Comment by codeslinger** [comment]
Re: testing: as far as the actual problem that existed prior to this PR, you should be able to:

1. Create a UDP socket
2. In one thread, send the socket some number of messages, `X`
3. In another thread, call `recvmmsg` with a number of `mmsghdr`s > `X` and a `flags` value of `MSG_DONTWAIT` (or `MSG_WAITFORONE` on Linux)

I can add a test for that to this PR if that seems acceptable.

**Comment by codeslinger** [comment]
Added a test for short reads when using `MSG_DONTWAIT`.

**Comment by asomers** [comment]
Looks good!  Could you also please add a CHANGELOG entry?

**Comment by asomers** [comment]
Actually, in the interest of expediency, I'm going to merge this now and add a CHANGELOG entry later.

**Review by asomers — APPROVED** [review]
bors r+

**Pull request merged**
