### PR TITLE
Support GETFPREGS and SETFPREGS ptrace calls

### PR DESCRIPTION
**Pull request by nemarci**
Added two new functions to the `ptrace` module: `getfpregs` and `setfpregs` gets and sets the floating point registers of the tracee.

### CODE REVIEW

**Review by asomers — CHANGES_REQUESTED** [review]
Would it be possible to add a test?

**Comment by nemarci** [comment]
> Would it be possible to add a test?

Yes, sure. What kind of test do you have in mind? I see that most ptrace related tests just call `ptrace` and then check that it doesn't return `Error::UnsupportedOperation`. Would a similar check be sufficient, or would you like some more thorough testing? (e.g. creating a subprocess, then modify one of the XMM reigsters with `setfpregs`, and reading it with `getfpregs` to check that we successfully modified it).

**Comment by asomers** [comment]
> > Would it be possible to add a test?
> 
> Yes, sure. What kind of test do you have in mind? I see that most ptrace related tests just call `ptrace` and then check that it doesn't return `Error::UnsupportedOperation`. Would a similar check be sufficient, or would you like some more thorough testing? (e.g. creating a subprocess, then modify one of the XMM reigsters with `setfpregs`, and reading it with `getfpregs` to check that we successfully modified it).

That would be perfect.

**Comment by nemarci** [comment]
Two of the automatic tests failed, but as far as I understand, these failures are unrelated to my patch. Could you verify if this is indeed true? And if I'm wrong, could you give some advice how to fix the failures?

**Comment by asomers** [comment]
Thanks for the very good tests!  As for the test failures, both should be fixed if you rebase your changes onto master.

**Comment by asomers** [comment]
Looks good, but I forgot one thing: this needs a CHANGELOG entry.  And you can go ahead and squash while you're at it.

**Comment by nemarci** [comment]
Closing in favor of https://github.com/nix-rust/nix/pull/1844

**Pull request closed without merging**
