### PR TITLE
Add wrapper for chmod

### PR DESCRIPTION
**Pull request by jmmv**
As the subject says, add a trivial wrapper for the chmod system call.

### CODE REVIEW

**Comment by asomers** [comment]
Welcome to Rust, Julio!  One question about this PR: can you give an example of when this function would be necessary as opposed to using [`std::os::unix::PermissionsExt::set_mode`](https://doc.rust-lang.org/std/os/unix/fs/trait.PermissionsExt.html#tymethod.set_mode) ?

**Comment by jmmv** [comment]
Hey! I know your name :)

Uh... well, never? Hadn't seen that yet. So I guess this is useless :-P

**Comment by jmmv** [comment]
Hold on... the `set_mode` you quote modifies a `Permissions` in-memory object... but how do you later apply those permissions to the actual file?

**Comment by asomers** [comment]
@jmmv see [`std::fs::set_permissions`](https://doc.rust-lang.org/std/fs/fn.set_permissions.html)

**Comment by jmmv** [comment]
Oh nice; thanks a lot. See https://github.com/jmmv/sandboxfs/commit/2dc36620fb2e90a84eade4deeb14bdc0c80e2898 for context.

**Pull request closed without merging**
