### PR TITLE
Add sched_getaffinity and sched_setaffinity on FreeBSD

### PR DESCRIPTION
**Pull request by rtzoeller**

### CODE REVIEW

**Comment by rtzoeller** [comment]
@asomers is there a way to define this or only run the tests for this on FreeBSD 13+?

**Comment by asomers** [comment]
> @asomers is there a way to define this or only run the tests for this on FreeBSD 13+?

Yeah, just guard the tests by `#[cfg(fbsd14)]`.  That's sufficient, since we don't do CI on FreeBSD 13.

**Review by asomers — APPROVED** [review]
LGTM, assuming you fix the test.

**Comment by rtzoeller** [comment]
bors r=asomers

**Comment by rtzoeller** [comment]
bors retry

**Pull request merged**
