### PR TITLE
Define UMOUNT_NOFOLLOW, FUSE_SUPER_MAGIC

### LINKED ISSUE #1631: Enhance mount::umount2 to support UMOUNT_NOFOLLOW flag
It would be great to enhance mount::umount2 to support UMOUNT_NOFOLLOW flag, so it could be used to defend some symlink based attacks.

### LINKED ISSUE #1633: Define sys::statfs::FUSE_SUPER_MAGIC for linux
The definition of FUSE_SUPER_MAGIC is missing, and libc has provided support of it.
https://github.com/rust-lang/libc/pull/2622

### PR DESCRIPTION
**Pull request by rtzoeller**
Resolves #1631 and resolves  #1633.

### CODE REVIEW

**Comment by rtzoeller** [comment]
Needs a changelog entry. Ideally this gets a libc release before being merged, but I wouldn't hold it for that alone.

**Comment by asomers** [comment]
LGTM, and the build failure is unrelated.

**Comment by rtzoeller** [comment]
@asomers how do you want to handle this deprecation, which is the source of the build failures? https://github.com/rust-lang/libc/commit/ef1787aa4b4ccf0a2fceeb290d12d2377bab4069

**Comment by asomers** [comment]
On FreeBSD and NetBSD, it's documented as "reserved by system".  I think we should just remove it from Nix.

**Pull request merged**
