### PR TITLE
Add support for TCP_KEEPCNT and TCP_KEEPINTVL TCP keepalive options.

### PR DESCRIPTION
**Pull request by yoav-steinberg**

### CODE REVIEW

**Comment by yoav-steinberg** [comment]
> At a minimum, this requires a CHANGELOG entry. Tests would also be welcome, if they make sense for these options.

Added CHANGELOG and simple tests.

**Review by asomers — CHANGES_REQUESTED** [review]
Better.  Sadly, there's a merge conflict.  You'll have to rebase.

**Comment by yoav-steinberg** [comment]
> Better. Sadly, there's a merge conflict. You'll have to rebase.

Rebased. Please review.

**Comment by gavrie** [comment]
@asomers It would be great to see this merged. Is anything additional required?

**Comment by asomers** [comment]
I think it looks good.  Just squash, please!

**Comment by yoav-steinberg** [comment]
Squashed.

**Review by asomers — CHANGES_REQUESTED** [review]
Somehow you lost the CHANGELOG when you squashed.

**Comment by yoav-steinberg** [comment]
> Somehow you lost the CHANGELOG when you squashed.

Squashed again.

**Review by asomers — APPROVED** [review]
bors r+

**Pull request merged**
