### PR TITLE
More cfg alias targets + disabled related clippy lint

### PR DESCRIPTION
**Pull request by Jan561**
Adds the remaining supported platforms as cfg alias.

This PR also disables this [lint].

## Checklist:

- [x] I have read `CONTRIBUTING.md`
- [x] I have written necessary tests and rustdoc comments
- [x] A change log has been added if this PR modifies nix's API

[lint]: https://rust-lang.github.io/rust-clippy/master/index.html#/mismatched_target_os

### CODE REVIEW

**Review by SteveLauC — APPROVED** [review]
Thanks!

**Comment by SteveLauC** [comment]
> Why is there a need for those aliases?

Yeah, they are currently not in use, should I revert this PR?

I merged this PR because it is trivial and maybe there will be a use case for it in the future, when we don't want those target_os = "xxx" stuff and fully switch to aliases

**Comment by asomers** [comment]
Yes, I think we should revert it , just so we can reenable that lint.  I've seen that lint fire correctly before.

**Comment by Jan561** [comment]
1. Either we use aliases for *all* supported targets, or we don't use them at all. Something in between is the worst option. I don't want to double check every time if there is a alias configured for the target.

2. #2210 already uses these aliases, and having to configure these in a PR when needing them feels wrong.

3. This lint is necessary if we want to use `#[cfg(linux)]` instead of `#[cfg(target_os = "linux")]`

**Comment by Jan561** [comment]
> > #2210 already uses these aliases, and having to configure these in a PR when needing them feels wrong.
> 
> This is my fault, I am sorry about it

All good, just need to tweak my codegen script a bit.

**Pull request merged**
