### PR TITLE
Add more errno definitions for better backwards compat with 0.21.0

### PR DESCRIPTION
**Pull request by asomers**
Fixes #1464

### CODE REVIEW

**Comment by asomers** [comment]
@sporksmith would the changes in this PR make the 0.21.0 -> 0.22.X upgrade easier for projects like yours?

**Comment by sporksmith** [comment]
Yes, it looks like this would've turned some of the errors into warnings. In our particular case there were few enough that I just fixed all the errors and warnings at once, but I imagine this could be helpful for other projects.

**Comment by sporksmith** [comment]
> Fixes #1464

Did you mean #1466? Btw there was another kind of error that looks like wasn't included in the truncated error list in the compiler output I shared there; will add on to #1466 since I think it'd be orthogonal to this PR.

**Pull request merged**
