### PR TITLE
Add getpagesize for linux

### PR DESCRIPTION
**Pull request by condy0919**
:)

### CODE REVIEW

**Comment by asomers** [comment]
Is this function really necessary?  It's in C because it predates `sysconf`.  But since Nix already has `sysconf`, I'm not sure there's any value to adding it.  It doesn't save the user any code.

**Comment by condy0919** [comment]
It can facilitate getting PAGESIZE without `unwrap` a `sysconf` call.
I think it helpful.

**Comment by asomers** [comment]
IMHO saving an `unwrap` is an insufficient reason to add a new function, especially one that's no longer even in POSIX.

**Comment by condy0919** [comment]
ok, I will close this pr

**Pull request closed without merging**
