### PR TITLE
stat fix unit tests for openbsd.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by asomers** [comment]
What was the problems?  Did these tests fail to compile, or fail at runtime?

**Comment by asomers** [comment]
The commit message is still pretty mysterious.  What's the real problem?

**Comment by devnexen** [comment]
it seems version related if I run an older version of openbsd the tests pass.

**Comment by asomers** [comment]
@devnexen did you ever figure out the root cause of your failures?

**Comment by devnexen** [comment]
well I lost the VM in the meantime, will look after when I can.

**Comment by asomers** [comment]
I'm closing this for lack of activity.  But if you ever do root-cause the issue, you can reopen it.

**Pull request closed without merging**
