### PR TITLE
Add AioCb::from_boxed_slice

### LINKED ISSUE #575: AioCb should work with refcounted buffers
The `AioCb` structure contains a reference (actually just a PhantomData) to a slice.  This makes it impossible to use in situations where the borrow checker can't prove that the slice will outlive the `AioCb`, such as with Tokio.  There should be a way to create `AioCb`s that use reference counted buffers instead.

### PR DESCRIPTION
**Pull request by asomers**
The existing AioCb constructors work for simple programs where
everything is stored on the stack.  But in more complicated programs the
borrow checker can't prove that a buffer will outlive the AioCb that
references it.  Fix this problem by introducting
AioCb::from_boxed_slice, which takes a reference-counted buffer.

Fixes #575

### CODE REVIEW

**Comment by Susurrus** [comment]
Can you rebase onto master and update this PR? The `new-ci/master` branch is only being used for developing the new CI framework.

**Comment by asomers** [comment]
Nope.  Can't rebase to master because of issue #567 .  But I can wait until new-ci/master is merged.

**Comment by Susurrus** [comment]
Indeed, hoping to merge it today.

**Comment by asomers** [comment]
Replaced by the rebased PR #582

**Pull request closed without merging**
