### PR TITLE
Improve AIO API

### PR DESCRIPTION
**Pull request by asomers**
- Turn most `aio_*` functions into `AioCb` methods
- Add runtime checks to `AioCb` methods
- Implement `Drop` for `AioCb`

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Thanks for the PR! I'm not familiar with POSIX AIO, so it'll take some time for me to review it. I don't know if any of the other maintainers are or not... @posborne @fiveop?

**Comment by asomers** [comment]
Some of these changes were requested by @posborne .  Perhaps he could review it?

**Comment by posborne** [comment]
@asomers Changes look good.  Can you look at addressing the OSX failure reported by CI?

**Comment by fiveop** [comment]
Given that there are no more OSX failures in the CI anymore, we should merge it. Since @posborne looked at the source, he should do it :)

**Comment by posborne** [comment]
@homu r+

**Pull request merged**
