### PR TITLE
PtyMaster::drop should panic on EBADF

### LINKED ISSUE #659: Potential double close in PtyMaster
`PtyMaster` implements `Drop` to close its `RawFd`.  However, it ignores errors, because the caller may have manually closed the `RawFd`.  This is bad, because it can lead to double closes, like this:
```
{
    let m = posix_openpt(O_RDWR);		# Creates a pty with file descriptor 3
    close(m.master);				# Close file descriptor 3
    let f = std::fs::File::create("foo");	# Creates a file with file descriptor 3
}						# PtyMaster::Drop closes file descriptor 3
f.write("whatever");				# fails with EBADF
```

There are three possible solutions:
1) Always check for errors in `PtyMaster::Drop`
2) Don't implement `PtyMaster::Drop`; make the caller responsible for closing it.  If we go this route, we should also add a `PtyMaster::close` method.
3) Change `PtyMaster` to wrap an `Option<RawFd>` and have the `close` method set it to `None`.  That way, the `drop` method will know whether to call `close`.

I prefer option 1, but I could go with any of these solutions.

### PR DESCRIPTION
**Pull request by asomers**
Fixes #659

### CODE REVIEW

**Comment by Susurrus** [comment]
LGTM. This bug was never in a released version of nix, so we're fine with no CHANGELOG entry.

Is it worth adding any doccomments somewhere that elaborate on this case so people understand what could happen? I'm not certain there is, but I wanted to make sure you thought about it.

**Comment by asomers** [comment]
I have no idea why i686-unknown-linux-musl keeps failing.  It passed 10,000 times in a row on my system.  QEMU is not to blame; i686 doesn't use it.  @Susurrus any ideas?

**Comment by Susurrus** [comment]
Please squash these into a single commit. And then it's r+ by me.

**Pull request merged**
