### PR TITLE
Replace try! with ?

### PR DESCRIPTION
**Pull request by asomers**
try! is not available in Rust 2018.  It would be premature to convert the entire project to Rust 2018, since that would bump the minimum compiler to 1.31.0.  But his change will help us when we do convert it eventually.

### CODE REVIEW

**Comment by Susurrus** [comment]
LGTM. However, what's the point of doing this now without a test checking that new PRs don't reintroduce these? I'd think it'd be easier if we moved to rust2018 in a concerted effort once we're willing to bump our Rust requirement to 1.31.

**Comment by asomers** [comment]
New PRs could absolutely break it.  But I had to do the work of building with Rust 2018 in order to make sure that Nix wouldn't cause any problems for dependent 2018 crates.  For example, another crate of mine had a public `try` method, so it couldn't easily be used by a 2018 crate.  I didn't find any problems, but since I had to make all of those changes anyway I figured I would push them.

**Comment by Susurrus** [comment]
I thought that there were no implications on other crates when setting the Rust edition? I guess that's not the case?

**Comment by asomers** [comment]
Technically there aren't.  But if the _consuming_ crate wants to use Rust 2018, then it would have an awkward time calling a Nix method called `try` or `async`.  It would have to call them like `foo.r#try()`, or something like that.  I wanted to make sure we would have no such pitfalls.

**Pull request merged**
