### PR TITLE
Reduce ios builds

### LINKED ISSUE #669: TravisCI is too slow
We have 34 builds in Travis, and it takes over an hour for all of them to finish.  It's causing Bors to timeout.  At a minimum, we need to increase bors's timeout.  Other ways to speed up the builds include:

1. Move i686-unknown-freebsd into BuildBot
2. remove `sudo: required`.  It causes Travis to use a full VM instead of a container, and I don't think we need it.
3. Only test beta and nightly builds on one architecture.
4. Enable parallel tests.  This will likely have minimal benefit, because setting up the environment is slower than running tests.
5. Use a custom Docker image so we won't have to download the QEMU stuff all the time
6. Set Travis's Auto Cancel Pull Requests feature

Any other ideas?

### PR DESCRIPTION
**Pull request by Susurrus**
Closes #669

### CODE REVIEW

**Comment by asomers** [comment]
Since we're not running tests on ios anyway, would it be possible to cross-build the ios targets from a Linux host?

**Comment by Susurrus** [comment]
Yeah, I'll test it locally and we'll switch to that if so.

**Comment by Susurrus** [comment]
```
$ rustup target install aarch64-apple-ios
$ cargo build --target aarch64-apple-ios
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target aarch64-apple-ios --crate-type bin --crate-type rlib` (exit code: 101)
--- stderr
error: Error loading target specification: Could not find specification for target "aarch64-apple-ios"
  |
  = help: Use `--print target-list` for a list of built-in targets
```

This is the error I get. I'd think cross-compiling would be possible, but I don't know what to do with this error. Any ideas?

**Comment by asomers** [comment]
I think you need to use `--target=foo`, not `--target foo`

**Comment by Susurrus** [comment]
That would've given me a different error. Both of those forms are equivalent.

**Comment by Susurrus** [comment]
This should be pretty uncontroversial.

bors r+

**Comment by asomers** [comment]
I get the same error.  It seems to me like rustup is installing std for aarch64-apple-ios, but not installing rustc.

**Comment by Susurrus** [comment]
See rust-lang/rustup.rs#1303

**Pull request merged**
