### PR TITLE
Optionally implement TryFrom in libc_enum!

### PR DESCRIPTION
**Pull request by asomers**
This saves code in several separate places that need to do this
separately.  At the same time, remove a few uses of mem::transmute that
were implementing TryFrom or similar functionality.

Issue #373

### CODE REVIEW

**Comment by Susurrus** [comment]
Sorry @asomers, but I'm not going to be able to review this. I've been out of the coding game for quite a while now, even giving up maintenance of `serialport-rs` in favor of other life pursuits. Hopefully some of the other maintainers can assist. I'm going to remove myself from the `nix-maintainers` team as well as I think that's appropriate at this stage. I have stayed on as I thought I might return, but at this point I don't think that's going to happen.

**Comment by asomers** [comment]
Out of the coding game entirely, as in even professionally?

**Review by asomers — COMMENTED** [review]
bors r+

**Comment by Susurrus** [comment]
I write very little code at work since about 4y now, only coding was for personal stuff. And I've realized I want to prioritize some other things. Appreciate working with you on this project and it was a great experience helping to build and maintain nix!

**Pull request merged**
