### PR TITLE
Omit invalid waitpid flags on OpenBSD

### PR DESCRIPTION
**Pull request by worr**
OpenBSD doesn't have `WEXITED`, `WSTOPPED`, or `WNOWAIT`, so omit those
from that platform.

### CODE REVIEW

**Comment by Susurrus** [comment]
We don't like to blacklist OS targets and instead follow a whitelist strategy. Please correct this to a whitelist for appropriate platforms.

The test failure is due to an upstream change in libc that needs to be fixed.

**Comment by worr** [comment]
I've updated the PR to be a whitelist of targets.

**Comment by Susurrus** [comment]
A few issues here:

- Please order the `target_os` OSes alphabetically.
- You have unrelated style changes wrapped up with functionality changes. This is widely considered bad-form with version control. Please separate this into two commits (their order doesn't matter) with your real code changes in one and style changes in the other.

**Comment by Susurrus** [comment]
Additionally, please rebase now that #790 was merged.

**Comment by worr** [comment]
Sorry about that, I messed up! I just pushed the latest rebased diffs.

**Comment by Susurrus** [comment]
No worries. But looking at this further, this seems to actually restrict these constants beyond OpenBSD. These three constants are available on haiku, ios, macos, and netbsd as well. Please re-add those platforms for those constants. You can search for them in the libc crate to see exactly which platforms support what for future reference.

**Comment by worr** [comment]
Whoops, I didn't think to check libc. Instead I checked the manpages, and it looks like I checked some out-of-date manpages.

I had no idea that y'all supported Haiku 😲

**Comment by Susurrus** [comment]
@worr We don't technically support Haiiku OS (though there is work in #772 to do just that), but I like to support things on all platforms that libc is supporting.

Anyways, thanks for cleaning this up. Was this all that was necessary for OpenBSD to build again?

bors r+

**Pull request merged**
