### PR TITLE
Add a document with contribution guidelines

### PR DESCRIPTION
**Pull request by kamalmarhubi**
This gives us a place to point new contributors, as well as to document
our project practices.

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
The part of this I'm really excited about is the issue labels. There are probably more to add, but here's a start!

**Comment by kamalmarhubi** [comment]
@abbradar as a new contributor, would a document like this be helpful?

**Comment by fiveop** [comment]
The \[homu\] link seems wrong.

**Comment by abbradar** [comment]
Several more things which might be useful:

1) Code style (basic things, like "4 spaces").
2) Policies w.r.t. new APIs that are more or less agreed upon (use `libc`, provide wrappers to `libc` structures where it sounds a good idea).
3) Testing policy (i.e. don't forget to run `cargo test` at least for your compiler and platform).

(BTW I'll continue working on my patches later, as I'm a bit short of time now)

**Comment by kamalmarhubi** [comment]
> The [homu] link seems wrong.

Fixed, and added a link to the queue as well.

**Comment by kamalmarhubi** [comment]
@abbradar thanks for the comments!

> 1) Code style (basic things, like "4 spaces").

I'm going to leave this out for now. I'm planning to make real progress on https://github.com/nrc/rustfmt/issues/434 and hopefully soon we'll be able to just say "run `cargo fmt-diff`" or whatever the command looks like.

> 2) Policies w.r.t. new APIs that are more or less agreed upon (use libc, provide wrappers to libc structures where it sounds a good idea).

I think these belong in the [conventions doc](https://github.com/nix-rust/nix/blob/master/CONVENTIONS.md). There's definitely more that needs to go in there though. Thanks for the suggestions!

> 3) Testing policy (i.e. don't forget to run cargo test at least for your compiler and platform).

Hm, I thought this would be implied by us having travis-ci set up. How do you think I could make it clearer?

**Comment by kamalmarhubi** [comment]
Also cc: @posborne :-)

**Comment by abbradar** [comment]
Travis forces the "tests should pass" policy but from my experience reminding that contributors should run final tests on their own machines somewhere can nevertheless reduce the volume of "Travis fails on this patch; can you please look?" messages from maintainers. An example would be yours truly -- I didn't have much Rust experience so I actually found out about `cargo test` _because_ Travis has failed on one of my patches. That said, there's good chance it's just me having poor contributing discipline -- I imagine one would look around and find out if there are tests and how to run them for any project they want to contribute to.

**Comment by arcnmx** [comment]
It's probably a decent idea to include a small section on testing. Something that describes how to run the tests and instructs contributors to include tests with their PR when appropriate, etc.

**Comment by posborne** [comment]
Agreed.  I am working on some additional test infrastructure for several of the more exotic targets (ARM, bsd, ...) and will do my best to come up with a solution that would allow for tests to be run locally (using docker, qemu, etc.) in a way that matches what Travis will be running.  This should make it easier to both contribute to those platforms and avoid regressions.

**Comment by kamalmarhubi** [comment]
@abbradar @arcnmx can you take another look?

**Comment by kamalmarhubi** [comment]
> That said, there's good chance it's just me having poor contributing discipline -- I imagine one would look around and find out if there are tests and how to run them for any project they want to contribute to.

No, your changes were great! This one's definitely on us. :-)

**Comment by kamalmarhubi** [comment]
@posborne 
> come up with a solution that would allow for tests to be run locally (using docker, qemu, etc.)

That would be so great.

**Comment by abbradar** [comment]
Looks good to me!

**Comment by arcnmx** [comment]
Looks good here too!

**Comment by fiveop** [comment]
The moment the merge conflict and the build failure (how can either happen, with a completely new file that is not code ...) are resolved I propose to merge this.

**Comment by kamalmarhubi** [comment]
I just squashed and rebased. Let's see how the on-behalf-of thing works.

@homu r=@fiveop

**Pull request merged**
