### PR TITLE
Add pthread_jit_write_protect api subset into sys::pthread

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Review by asomers — COMMENTED** [review]
It doesn't seem like these bindings add a whole lot of value.  Is it really necessary to have them in Nix?

**Comment by devnexen** [comment]
In fact, those are necessary on mac arm64 (not much on amd64) if you do mapping with execution and write bits.

**Comment by asomers** [comment]
But it is necessary for those functions to be `in Nix` as opposed to remaining in libc.  Because all your bindings do is call the libc function, which a consumer could do just as well.

**Comment by devnexen** [comment]
good point.

**Pull request closed without merging**
