### PR TITLE
Conditionally enable functionality with feature flags

### PR DESCRIPTION
**Pull request by asomers**
This PR satisfies a long-running request: to slim down the Nix crate by conditionally enabling certain functionality.  By default everything is enabled, but consumers can reduce that by selecting a subset of features.

### CODE REVIEW

**Comment by asomers** [comment]
I think I addressed all of your comments.  HOWEVER, rustdoc's behavior just changed, which will require revisiting every part of this PR.  I'm working on that now.
https://github.com/rust-lang/rust/pull/89596

**Comment by rtzoeller** [comment]
One other note: if you've considered updating the codebase to use `rustfmt`/`cargo fmt`, doing it immediately following the submission of this PR might be a good idea. This change will likely cause most existing PRs to require resolving conflicts anyways.

**Comment by rtzoeller** [comment]
@asomers I think we should consider whether or not we expect tests with just some features enabled to work.

E.g. should `cargo test --no-default-features --features fs` build successfully, and run just the `fs`-related tests?

I'm also fine with saying "ideally yes, but not in this PR".

**Comment by asomers** [comment]
> @asomers I think we should consider whether or not we expect tests with just some features enabled to work.
> 
> E.g. should `cargo test --no-default-features --features fs` build successfully, and run just the `fs`-related tests?
> 
> I'm also fine with saying "ideally yes, but not in this PR".

It would be nice.  OTOH it would clutter up the test files with a lot of `#[cfg()]` directives, which is why I didn't do it originally.  I don't think it's necessary, because I can't see any way that disabling features could cause the tests to fail, as long as they compile.  Can you?

**Pull request closed without merging**
