### PR TITLE
PTRACE_GETREGSET and PTRACE_SETREGSET basic implementation on aarch64

### PR DESCRIPTION
**Pull request by irgstg**
As I mentioned in https://github.com/nix-rust/nix/issues/1419#issuecomment-1094251694 I had this code implemented in a personal project of mine.

As some of you might know, to read and modify tracee's registers with `ptrace` on `aarch64`, one need to do so by calling `ptrace` via `iovec`. ([man ptrace](https://linux.die.net/man/2/ptrace) under `PTRACE_GETREGSET`)

This current PR supports `aarch64` linux and android and includes:
- Two generic `ptrace` calls to receive and modify data via `iovec`: `ptrace_get_iovec_data` and `ptrace_set_iovec_data`.
- Two pub functions that supports modify and read of tracee's registers: `ptrace_getregset` and `ptrace_setregset`
- Test function, `test_ptrace_regsets`, that receives tracee's registers, modify one of them, and validate if the modification completed successfully. 

I might will modify some minor changes.

I want to get you're special attention about this line from `man ptrace`:
_On return, the kernel modifies iov.len to indicate the actual number of bytes returned._
In my original implemented I didn't add anything to validate that, and I'm not aware what'd this repo's conventions dictate in such occasion, so leave a comment and I will edit the code as necessery.

Please let me know if I forgot or missed something.

### CODE REVIEW

**Comment by tiann** [comment]
any updates?

**Comment by 2096779623** [comment]
Can someone review this?

**Comment by SteveLauC** [comment]
Hi, plan to take a look at this PR this weekend, sorry for being so late, and I am not sure if we can have @irgstg back as it has been 2 years, if not, I will file a PR to supersede this one.

**Comment by SteveLauC** [comment]
I tend to merge #2044 as it:

1. Allows users to specify the register set
2. Has `riscv64` supported as well

@irgstg, thanks for your work and [this detailed description](https://github.com/nix-rust/nix/pull/1695#issue-1199014612), it helps a lot! And I am sorry that I will close this PR:<

**Pull request closed without merging**
