### PR TITLE
musl target needs std::mem now

### PR DESCRIPTION
**Pull request by fiveop**
Closes nix-rust/nix#325.

### CODE REVIEW

**Comment by fiveop** [comment]
This build and the build for PR #379 only failed because of timeouts on mac builds. This is probably due to Travis-CI's recent problems with MacOS builds. Does anyone of us have the privileges to trigger a rebuild without us having to reopen the PR or push a change?

**Comment by fiveop** [comment]
Since this change should not have any impact on our CI builds, could you, @posborne, recheck that it builds properly for x86_64-unknown-linux-musl now?

**Comment by utkarshkukreti** [comment]
I have triggered a rebuild for this PR: https://travis-ci.org/nix-rust/nix/builds/141162721

I think you should be able to do it too from https://travis-ci.org/nix-rust/nix/pull_requests.

**Comment by fiveop** [comment]
Thanks. I do not see any UI element on that page, that would allow me to rebuild a previous build.

**Comment by utkarshkukreti** [comment]
Are you logged in on Travis? Click on a PR title on that page and you should see a "Restart Build" icon on the right like this:

screen shot 2016-06-30 at 10 33 53 pm

**Comment by utkarshkukreti** [comment]
@homu r+

**Pull request merged**
