### PR TITLE
Add support for Solaris platform

### PR DESCRIPTION
**Pull request by nbaksalyar**
This PR adds preliminary support for the Solaris/Illumos-derived operating systems (SmartOS, OmniOS, and others) and lays a foundation for adding more Solaris-specific features (like e.g. [event ports](https://blogs.oracle.com/barts/entry/entry_2_event_ports) for subsequent _mio_ port).

However, though patched version builds OK, it doesn't pass the full test suite yet. So more updates & patches coming soon. :)

### CODE REVIEW

**Comment by fiveop** [comment]
Thank you. We do not have a CI build for solaris, so we do not officially support it. I still would not mind merging your changes. I would appreciate you using constants from libc in all possible cases. A cursory `git grep` over libc sources shows, that at least some further constants (`EPERM`, etc.) are defined for solaris already, and getting missing constants merged is pretty easy for libc.

**Comment by nbaksalyar** [comment]
>We do not have a CI build for solaris, so we do not officially support it.
How can I help with it? As I understand it, currently you're using a combination of Docker, multirust, and Travis CI for tests?

>I would appreciate you using constants from libc in all possible cases.
Could you please point me to an example? E.g. from what I gather `EPERM` isn't imported from libc for other platforms, or is it just a legacy approach?

>getting missing constants merged is pretty easy for libc.
Sure! I already commited & merged some, but what should go in _nix_ is still a bit confusing for me, as I write Solaris/Illumos-specific code based on code for other platforms.

**Comment by fiveop** [comment]
> How can I help with it? As I understand it, currently you're using a combination of Docker, multirust, and Travis CI for tests?

I have no experience with setting them up. I would look at our .travis.yml file and search the internet for how it's done from there. @posborne should be able to give you proper help, if you have questions. We certainly would appreciate CI contributions for as of yet uncovered platforms.

> Could you please point me to an example? E.g. from what I gather EPERM isn't imported from libc for other platforms, or is it just a legacy approach?

As mentioned in CONVENTIONS.md, we would like to not have any constants defined in nix itself. I know that the code of nix is not there yet.

**Comment by posborne** [comment]
Yeah, I think best bet for testing platforms like BSD/Solaris/... will be to use qemu.  This is what the libc crate does: https://github.com/rust-lang/libc/tree/master/ci.  Adding solaris to libc will be a good first step and a prerequisite to considering Solaris an officially supported platform of nix (we rely heavily on libc and libc does verifications that we do not).

**Comment by nbaksalyar** [comment]
OK, thank you for the clarification!
Then I'm going to add tests for the x86_64-sun-solaris platform in _libc_ first and then change this patch to import constants. Feel free to close this PR for now.

**Comment by posborne** [comment]
Closing for now.

**Pull request closed without merging**
