### PR TITLE
Disable clock_getres on redox

### PR DESCRIPTION
**Pull request by coolreader18**

### CODE REVIEW

**Review by asomers — CHANGES_REQUESTED** [review]
Could you please explain why, and also add an entry to CHANGELOG?

**Comment by coolreader18** [comment]
Should I explain why as a comment in the code, or just here? If the latter, it's because `clock_getres` isn't available on Redox, so `nix` would fail to compile when targeting Redox.

**Comment by asomers** [comment]
Except that it doesn't fail.  We build for Redox in CI.  Why does that pass, but whatever you're doing does not?

**Comment by coolreader18** [comment]
Huh, really? Weird... here's the error I get:
```
    Checking nix v0.19.0
error[E0425]: cannot find function `clock_getres` in crate `libc`
    --> /home/coolreader18/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.19.0/src/time.rs:209:30
     |
209  |     let ret = unsafe { libc::clock_getres(clock_id.as_raw(), c_time.as_mut_ptr()) };
     |                              ^^^^^^^^^^^^ help: a function with a similar name exists: `clock_gettime`
     | 
    ::: /home/coolreader18/.cargo/git/checkouts/libc-d1297d136f47e864/d588f99/src/unix/redox/mod.rs:1061:5
     |
1061 |     pub fn clock_gettime(clk_id: ::clockid_t, tp: *mut ::timespec) -> ::c_int;
     |     -------------------------------------------------------------------------- similarly named function `clock_gettime` defined here
```

**Comment by coolreader18** [comment]
I guess I'm building under redoxer, whereas CI builds just using cross-compilation.

**Comment by coolreader18** [comment]
It's strange though, because `libc` *doesn't* define `clock_getres` for redox:
```
libc on  master is 📦 v0.2.80 via 🦀 v1.49.0-nightly took 3s 
❯ rg clock_getres src/unix/redox

libc on  master is 📦 v0.2.80 via 🦀 v1.49.0-nightly 
❯ 
```

**Comment by asomers** [comment]
Nope, it's our mistake.  There's an error in the Travis file.  Could you please add this to your PR?
```diff
--- a/.travis.yml
+++ b/.travis.yml
@@ -104,7 +104,7 @@ matrix:
         - curl --proto '=https' --tlsv1.2 -sSf --output rustup.sh https://sh.rustup.rs
         - sh rustup.sh -y --profile=minimal --default-toolchain 1.36.0 --target x86_64-unknown-redox
         - . $HOME/.cargo/env
-        - cargo build --all-targets
+        - cargo build --target x86_64-unknown-redox --all-targets
 
 before_install: set -e
 ```

**Comment by asomers** [comment]
You'll have to rebase to fix the CI errors, not to mention the merge conflict.

**Comment by asomers** [comment]
@coolreader18 did you notice the build failures for Redox?  I think you'll have to switch Redox's compiler to nightly.  libc seems to require it.

**Comment by coolreader18** [comment]
Ah, alright

**Comment by asomers** [comment]
Since Travis has been working so poorly this week, I'm working on replacing it.  I've pulled your changes into PR #1350 .  Let's continue there.

**Pull request closed without merging**
