### PR TITLE
Add more platforms to CI

### PR DESCRIPTION
**Pull request by Susurrus**
* aarch64-unknown-linux-musl
 * sparc64-unknown-linux-gnu
 * x86_64-unknown-linux-gnux32

These don't pass yet, but should be supportable by `nix`, so let's add them now as platforms that are allowed to fail so we can move towards fully supporting them.

### CODE REVIEW

**Comment by Susurrus** [comment]
Not certain why these weren't working by just adding them. Tried hacking them in, but need to come back and relearn our CI setup to actually get these fixed.

**Comment by asomers** [comment]
Don't forget to add new platforms to the README, if we're going to support them.

**Comment by Susurrus** [comment]
Coming back to this now, so rebased and updated the CHANGELOG and README, but will likely wait until #1035 is merged to really dig into why these platforms are failing.

**Comment by SteveLauC** [comment]
Close this PR for the same reason as #2255

**Pull request closed without merging**
