### PR TITLE
fix(unsafe): remove unnecessary unsafe

### PR DESCRIPTION
**Pull request by matu3ba**
libc 0.2.82 exposes status signals with macros generating safe functions

### CODE REVIEW

**Comment by matu3ba** [comment]
fixes #1380 

Should I also write this in the PR ?

**Review by asomers — CHANGES_REQUESTED** [review]
Please don't mix content and formatting changes in a single commit.

**Comment by matu3ba** [comment]
@asomers should be fixed.

**Review by asomers — APPROVED** [review]
bors r+

**Pull request merged**
