### PR TITLE
Restore conversions from ip v4/6 Sockaddr types to std::net equivalents.

### LINKED ISSUE #1710: InetAddr replacements are not convertible to libstd types?
Apologies if I've overlooked something here.

The now deprecated `nix::sys::socket::InetAddr` has a `to_std` method on it. The replacement `Sockaddrin`/`Sockaddrin6` don't appear to have any equivalent functionality.

### PR DESCRIPTION
**Pull request by khuey**
Fixes #1710

### CODE REVIEW

**Comment by asomers** [comment]
How about a mention in the `Added` section of `CHANGELOG`?

**Comment by rtzoeller** [comment]
@khuey can you rebase to fix the CHANGELOG conflict? I updated the file with the expected format in another PR.

**Comment by khuey** [comment]
> @khuey can you rebase to fix the CHANGELOG conflict? I updated the file with the expected format in another PR.

Done

**Review by asomers — APPROVED** [review]
LGTM

bors r+

**Pull request merged**
