### PR TITLE
Renable the ScmTimestamp test on FreeBSD i386

### PR DESCRIPTION
**Pull request by asomers**
The relevant bug was fixed in 11.3-RELEASE

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222039

### CODE REVIEW

**Review by posborne — APPROVED** [review]
bors r+

**Comment by asomers-ax** [comment]
Failed due to an intermittent network problem.

bors retry

**Comment by posborne** [comment]
bors retry

**Comment by asomers-ax** [comment]
Thank you posborne.  Github is a little more annoying now that I have two accounts.

**Comment by asomers** [comment]
Another download failure from cross.

bors retry

**Pull request merged**
