### PR TITLE
Update RELEASE_PROCEDURE.md

### PR DESCRIPTION
**Pull request by Susurrus**
Based on discussion after the 0.10.0 release.

### CODE REVIEW

**Comment by Susurrus** [comment]
@asomers @posborne This is a relatively minor change, any feedback here?

**Comment by Susurrus** [comment]
@asomers This was implemented in BuildBot as well: https://github.com/buildbot/buildbot/pull/3443 Is it in the version you're running?

**Comment by asomers** [comment]
Looks like it, since buildbot didn't build this PR.

**Comment by Susurrus** [comment]
@asomers Can I get a LGTM?

**Comment by asomers** [comment]
Yep.

bors r+

**Pull request merged**
