### PR TITLE
test/test_stat.rs: test correct stat function

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by Susurrus** [comment]
@mic92 good catch! This LGTM, but I wanted to ask if you could fix the temp folder name for the `test_fstatat` function to be different from the above test as well. Looks like a copy/paste error when it was added. Once that's done here, I'm r+.

**Comment by Mic92** [comment]
Changed via the github web editor (which is also writeable as reviewer and create to fix unrelated nitpicks).

**Comment by Susurrus** [comment]
@Mic92 Thanks for adding that.

Alright, this is minor and looks fine to me.

bors r+

**Comment by asomers** [comment]
Again, the timeout was due to the submitter's umlaut.  I'll manually merge it.

**Comment by Mic92** [comment]
python and unicode..

**Pull request merged**
