### PR TITLE
use better merge algorithm for CHANGELOG.md

### PR DESCRIPTION
**Pull request by Mic92**
see also: https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/

### CODE REVIEW

**Comment by asomers** [comment]
Cool!  I had no idea that was possible.  Let's hope it works.

bors r+

**Comment by Mic92** [comment]
I already used that to merge all my pull requests into one.

**Comment by asomers** [comment]
It's buildbot's problem, not bor's.  Buildbot can't handle your umlaut.  Curiously, the umlaut isn't a problem when building pull requests, only when merging them.  I'll merge manually.

**Pull request merged**
