### PR TITLE
readme: Add gitter badge

### PR DESCRIPTION
**Pull request by kamalmarhubi**
I created the `nix-rust` gitter community and a channel for the nix repo. This adds a badge and link to the README.

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
@nix-rust/nix-maintainers do we want to do this?

**Comment by Susurrus** [comment]
I think a bitter is good, but I don't know how to present this to users and devs. Maybe an explicit Communication section of the readme instead of putting that badge at the top.

Related to this does anyone have any (at least short term) plans to check in on the channel every so often?

**Comment by kamalmarhubi** [comment]
Yeah I'll add something in the readme. The second question is definitely important, and why I wanted input.

**Comment by Susurrus** [comment]
I'll check in every so often. I already use it for coordinating with the retep998/winapi-rs and gtk-r/gtk repos, and while they aren't very active, they're helpful for a direct communication channels with the devs.

**Comment by Susurrus** [comment]
Let's go ahead and merge this. I've already used it with @asomers. Nobody's suggested any reason it's a bad idea. If I don't hear anything by Monday, I'm going to merge.

**Pull request closed without merging**
