### PR TITLE
Add RISC-V support on GNU/Linux

### PR DESCRIPTION
**Pull request by msizanoen1**

### CODE REVIEW

**Comment by asomers** [comment]
How does one build this?  Does rustup include a risc-v toolchain now?

**Comment by msizanoen1** [comment]
No but libc and libstd are ported.
You can get a RISC-V cross toolchain and use xargo or cargo's `-Zbuild-std`.

**Comment by msizanoen1** [comment]
This is the PR for building rust libstd on CI: https://github.com/rust-lang/rust/pull/68037
After it is merged you can install it from rustup.

**Comment by asomers** [comment]
What exactly does this PR accomplish?  Is there more to it than those handfuls of constants?

**Comment by msizanoen1** [comment]
That's everything needed to make it compile on RISC-V.

**Pull request merged**
