### PR TITLE
nix::InterfaceAddress: adding interface information if it is UP.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Review by SteveLauC — APPROVED** [review]
Looks good, thanks! CI failures are not related, I will handle them.

**Review by SteveLauC — COMMENTED** [review]
Well, perhaps I need a reason for this change even though it is ok and trivial, we already have this info in `addr.flags.contains(InterfaceFlags::IFF_UP)`.

I think we need to consider what should be stored in the struct, currently, all the stored fields come from the libc struct `libc::ifaddrs`.

**Comment by devnexen** [comment]
well, we can consider extra fields as info access aliases/shortcuts wdyt ?

**Comment by SteveLauC** [comment]
> we can consider extra fields as info access aliases/shortcut

I am thinking that if getting this info is already straightforward, then there is no need to add a shortcut for it 😶

**Comment by SteveLauC** [comment]
CI fixed in #2470

**Comment by devnexen** [comment]
Sure, anyway up to you if you want to merge it, no hard feeling if you don't :)

**Comment by SteveLauC** [comment]
Thanks for the understanding ❤️, I will close this PR then:)

**Pull request closed without merging**
