### PR TITLE
Impl `AsRawFd` for `OwningIter`

### PR DESCRIPTION
**Pull request by deantvv**
For issue #1558

### CODE REVIEW

**Comment by asomers** [comment]
I think this is a reasonable addition.  Could you add a CHANGELOG entry please?

**Comment by deantvv** [comment]
@asomers CHANGELOG updated.

**Comment by rtzoeller** [comment]
@deantvv can you rebase to fix the changelog conflict? Thanks!

**Comment by deantvv** [comment]
@rtzoeller Just rebased to resolved CHANGELOG conflict.

**Pull request merged**
